### ISSUE TITLE
不能正确定位秋季开学时间

### ISSUE THREAD

**Issue by Jackhr-arch** [MarvinTerry/HustLogin#19]
使用按周查询（int方法）时，可以看到返回值从2月份起而非8月。这导致不能正常查询秋季课程表

**Comment by Jackhr-arch** [comment]
另外，你可以把两个readme里的SVG删了，或者换成CI的

**Comment by MarvinTerry** [comment]
已通过增加学期参数解决

估计学校会在开学后把默认学期改到20231
